interface ReconstituteProps {
  readonly id: string;
  readonly documentId: string;
  readonly companyId: string;
  readonly chunkIndex: number;
  readonly content: string;
  readonly qdrantPointId: string;
  readonly chunkHash: string;
  readonly embeddingModel: string | null;
  readonly createdAt: Date;
}

/**
 * `id` is null until persisted — the database generates it. `qdrantPointId`
 * is different: it must exist BEFORE the Qdrant upsert happens (Qdrant
 * needs a point id up front), so it's generated by the caller (the
 * GenerateChunksJob) and passed in here, not left to the DB.
 */
export class DocumentChunkEntity {
  private constructor(
    public readonly id: string | null,
    public readonly documentId: string,
    public readonly companyId: string,
    public readonly chunkIndex: number,
    public readonly content: string,
    public readonly qdrantPointId: string,
    public readonly chunkHash: string,
    public readonly embeddingModel: string | null,
    public readonly createdAt: Date,
  ) {}

  static create(
    documentId: string,
    companyId: string,
    chunkIndex: number,
    content: string,
    chunkHash: string,
    qdrantPointId: string,
  ): DocumentChunkEntity {
    return new DocumentChunkEntity(null, documentId, companyId, chunkIndex, content, qdrantPointId, chunkHash, null, new Date());
  }

  static reconstitute(props: ReconstituteProps): DocumentChunkEntity {
    return new DocumentChunkEntity(
      props.id,
      props.documentId,
      props.companyId,
      props.chunkIndex,
      props.content,
      props.qdrantPointId,
      props.chunkHash,
      props.embeddingModel,
      props.createdAt,
    );
  }

  withEmbeddingModel(model: string): DocumentChunkEntity {
    return new DocumentChunkEntity(
      this.id,
      this.documentId,
      this.companyId,
      this.chunkIndex,
      this.content,
      this.qdrantPointId,
      this.chunkHash,
      model,
      this.createdAt,
    );
  }
}
