export const REPOSITORY_TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  COMPANY_REPOSITORY: 'COMPANY_REPOSITORY',
  API_KEY_REPOSITORY: 'API_KEY_REPOSITORY',
  AI_CONFIGURATION_REPOSITORY: 'AI_CONFIGURATION_REPOSITORY',
  DOCUMENT_REPOSITORY: 'DOCUMENT_REPOSITORY',
  DOCUMENT_CHUNK_REPOSITORY: 'DOCUMENT_CHUNK_REPOSITORY',
  DATA_TABLE_REPOSITORY: 'DATA_TABLE_REPOSITORY',
  DATA_TABLE_ROW_REPOSITORY: 'DATA_TABLE_ROW_REPOSITORY',
  CONVERSATION_REPOSITORY: 'CONVERSATION_REPOSITORY',
  MESSAGE_REPOSITORY: 'MESSAGE_REPOSITORY',
  PLAN_REPOSITORY: 'PLAN_REPOSITORY',
  SUBSCRIPTION_REPOSITORY: 'SUBSCRIPTION_REPOSITORY',
} as const;

export const PROVIDER_TOKENS = {
  PASSWORD_HASHER: 'PASSWORD_HASHER',
  TOKEN_PROVIDER: 'TOKEN_PROVIDER',
  API_KEY_HASHER: 'API_KEY_HASHER',
  STORAGE_PROVIDER: 'STORAGE_PROVIDER',
  AI_PROVIDER: 'AI_PROVIDER',
  EMBEDDINGS_PROVIDER: 'EMBEDDINGS_PROVIDER',
  VECTOR_STORE: 'VECTOR_STORE',
  VECTOR_INDEXER: 'VECTOR_INDEXER',
  SQL_AGENT: 'SQL_AGENT',
} as const;
